# This service requests that a camera stores the given CameraInfo 
# as that camera's calibration information.

# The width and the height in the camera_info field have to match the width
# and height that the camera is currently publishing in its camera_info
# topic.

# The camera assumes that the camera_info field refers to to the same
# region of pixels on the imager as the camera_info topic that is currently
# being published.

sensor_msgs/CameraInfo camera_info # The camera_info to store
---
bool success          # True if the call succeeded
string status_message # Used to give details about success
