(cl:in-package visualization_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          NS-VAL
          NS
          ID-VAL
          ID
          TYPE-VAL
          TYPE
          ACTION-VAL
          ACTION
          POSE-VAL
          POSE
          SCALE-VAL
          SCALE
          COLOR-VAL
          COLOR
          LIFETIME-VAL
          LIFETIME
          FRAME_LOCKED-VAL
          FRAME_LOCKED
          POINTS-VAL
          POINTS
          COLORS-VAL
          COLORS
          TEXT-VAL
          TEXT
          MESH_RESOURCE-VAL
          MESH_RESOURCE
          MESH_USE_EMBEDDED_MATERIALS-VAL
          MESH_USE_EMBEDDED_MATERIALS
))