Header header        # Header
string label         # Label for the image
string encoding      # Specifies the color encoding of the data
                     #   Acceptable values are:
                     #    1 channel types:
                     #     mono
                     #    3 channel types:
                     #     rgb, bgr
string format        # Specifies the format of the data
                     #   Acceptable values:
                     #     jpeg

std_msgs/UInt8MultiArray   uint8_data
